import folium

m = folium.Map(
  location=[4.695135,   96.749397],
  zoom_start=10,)

folium.Marker(
  location=[4.629343, 96.787586],
  popup='Kabupaten Aceh Tengah',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.377438, 97.161121],
  popup='Linge',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[5.403978, 94.8649394],
  popup='Kabupaten Aceh Besar',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[5.521737, 95.267446],
  popup='Peukan Bada',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[5.540874, 95.424001],
  popup='Kuta Baro',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.892097, 96.117719],
  popup='Kabupaten Pidie',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.662186, 97.414106],
  popup='Serba Jadi',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[5.078158, 95.908979],
  popup='Tangse',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.738831, 96.216596],
  popup='Sungai MAS',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[3.094788, 97.765668],
  popup='Hutan',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.7747372, 96.7121891],
  popup='Kab. Bener Meriah',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.7025774, 97.0787132],
  popup='Kab. Aceh Timur',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.993586, 96.8704841],
  popup='Kab. Aceh Utara',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[3.8354523, 96.5870526],
  popup='Kab. Aceh Barat Daya',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[3.0700274, 96.8644272],
  popup='Kab. Aceh selatan',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[3.3379887, 97.0568133],
  popup='Kab. Aceh Tenggara',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.2184441, 97.7212565],
  popup='Kab. Aceh Tamiang',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[3.9808591, 96.7630114],
  popup='Kab. Aceh GayoLues',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.788100, 96.381874],
  popup='Rusip Antara. Kabupaten Aceh Tengah',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.5092677,96.1253181,15],
  popup='Jl. Geumpang-Tutut',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[5.385298,95.2575132,14],
  popup='Jl. Banda aceh-Calang',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[5.5589877,95.3220353,15],
  popup='Tugu Simpang Lima Banda Aceh',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[5.535423,95.3905828,13],
  popup='Bandara Internasional Sultan Iskandar Muda',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[5.4710423,95.4069452,16],
  popup='PT.POS (Persero) Montasik',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[5.5484305,95.3153775,13],
  popup='Masjid Raya Baiturrahman',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[5.6279369,95.1505769,10]
  popup='Suka Makmur',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[5.5442072,95.5000587,12]
  popup='Pemandian Air Panas Aceh Besar',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[5.4887222,95.2206677],
  popup='Surf Cafe Lampuuk Beach',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[5.4887222,95.2206677],
  popup='Lampuuk Beach',
  icon=folium.Icon(icon='info-sign')
).add_to(m)


folium.Marker(location=[5.868271, 95.332800],popup='Sabang',icon=folium.Icon(icon='info-sign')).add_to(m)
folium.Marker(location=[5.901489, 95.220230],popup='Iboih',icon=folium.Icon(icon='info-sign')).add_to(m)
folium.Marker(location=[5.906413, 95.218188],popup='Unnamed Road',icon=folium.Icon(icon='info-sign')).add_to(m)
folium.Marker(location=[5.882337, 95.257476],popup='Pulau Rubiah',icon=folium.Icon(icon='info-sign')).add_to(m)
folium.Marker(location=[5.895571, 95.253356],popup='Pulau Seulako',icon=folium.Icon(icon='info-sign')).add_to(m)
folium.Marker(location=[5.846136, 95.275071],popup='Batee Shoek',icon=folium.Icon(icon='info-sign')).add_to(m)
folium.Marker(location=[5.824106, 95.279019],popup='Paya',icon=folium.Icon(icon='info-sign')).add_to(m)
folium.Marker(location=[5.879597, 95.340429],popup='Ujong Kareung',icon=folium.Icon(icon='info-sign')).add_to(m)
folium.Marker(location=[5.850618, 95.345770],popup='Cot Abeuk',icon=folium.Icon(icon='info-sign')).add_to(m)
folium.Marker(location=[5.862454, 95.340713],popup='Pulau We',icon=folium.Icon(icon='info-sign')).add_to(m)


folium.Marker(
  location=[4.021332, 96.827483],
  popup='Persada Tongra Terangun, Kabupaten Gayo Lues',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.508936, 96.126242],
  popup='Geudong',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.490047, 96.205635],
  popup='Panton Reu',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.501000, 96.029854],
  popup='Woyla Tim.',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.862339, 95.810127],
  popup='Krueng Sabee',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.873285, 95.705757],
  popup='Gampong Baroh',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.993687, 95.623360],
  popup='Sampoiniet',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.692642, 95.760689],
  popup='Panga',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.829497, 96.024361],
  popup='Mane',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.424329, 96.392403],
  popup='Pantai Ceuremen',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.254529, 96.293526],
  popup='Seunagan',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.5065868, 97.9302927],
  popup='Langsa, Kota Langsa',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[5.1720572, 97.0375946],
  popup='	Kota Lhokseumawe',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[5.9670211, 5.0957705],
  popup='Kota Sabang',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[2.7578791, 97.6614605],
  popup='Kota Subulussalam',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.4520047, 95.9055919],
  popup='Kabupaten Aceh Barat',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.8122858, 95.1058125],
  popup='Kabupaten Aceh Jayat',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.6338398, 95.5730575],
  popup='Calang, Bahagia, Kabupaten Aceh Jaya',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[5.186493,95.5404471],
  popup='Kota Jantho',
  icon=folium.Icon(icon='info-sign')
).add_to(m)
folium.Marker(
  location=[4.3313354, 97.9990071],
  popup='Karang Baru',
  icon=folium.Icon(icon='info-sign')
).add_to(m)



m.save('index.html')
